# --------------------------------------------------------------------------------------
# This code is part of SpinPulse.
#
# (C) Copyright Quobly 2025.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.
# --------------------------------------------------------------------------------------
"""
The `environment` module provides a set of classes for defining and configuring a quantum experimental environment tailored to spin-qubit systems.

    - :mod:`spin_pulse.environment.experimental_environment`, defines the `Environment` class that contains a quantum experimental environment with configurable noise models.

    The submodule :mod:`spin_pulse.environment.noise` provides a set of noise classes for simulating different noise processes:
        - QUASISTATIC: Quasistatic noise generated by `QuasistaticNoiseTimeTrace`.
        - PINK: Pink (1/f) noise generated by `PinkNoiseTimeTrace`.
        - WHITE: White Gaussian noise generated by `WhiteNoiseTimeTrace`.
"""
