# --------------------------------------------------------------------------------------
# This code is part of SpinPulse.
#
# (C) Copyright Quobly 2025.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.
# --------------------------------------------------------------------------------------
"""
This modules provides a set of noise classes for simulating different noise processes:
    - QUASISTATIC: Quasistatic noise generated by `QuasistaticNoiseTimeTrace` from :mod:`spin_pulse.environment.noise.quasistatic`.
    - PINK: Pink (1/f) noise generated by `PinkNoiseTimeTrace` from :mod:`spin_pulse.environment.noise.pink`.
    - WHITE: White Gaussian noise generated by `WhiteNoiseTimeTrace` from :mod:`spin_pulse.environment.noise.white`.
"""

from .noise_time_trace import NoiseTimeTrace, NoiseType
from .pink import PinkNoiseTimeTrace
from .quasistatic import QuasistaticNoiseTimeTrace
from .white import WhiteNoiseTimeTrace

__all__ = [
    "NoiseTimeTrace",
    "NoiseType",
    "PinkNoiseTimeTrace",
    "QuasistaticNoiseTimeTrace",
    "WhiteNoiseTimeTrace",
]
